---
- hosts: all
  become: true

  tasks:
  - name: stop container
    command: docker container stop docker-container
    ignore_errors: yes

  - name: remove container
    command: docker container rm docker-container
    ignore_errors: yes

  - name: remove images
    command: docker image rm arimaverick/devops-simple-image:1.0
    ignore_errors: yes

    #- name: build docker image from war file
    #command: docker build -t devops-simple-image:1.0 .
    #args:
    #  chdir: /opt/docker

  - name: pull docker image from dockerhub
    command: docker pull arimaverick/devops-simple-image:1.0

  - name: build container out of this image
    command: docker run -d --name docker-container -p 8080:8080 arimaverick/devops-simple-image:1.0
